version: '3.7'

services:
  medic-os:

    image: medicmobile/medic-os:cht-3.9.0-rc.2
    volumes:
      - "${CHT_DATA:-medic-data}:/srv"
    ports:
      - "${CHT_HTTP:-80}:80"
      - "${CHT_HTTPS:-443}:443"
    working_dir: /srv
    depends_on:
      - haproxy
    environment:
      - DOCKER_NETWORK_NAME=haproxy
      - DOCKER_COUCHDB_ADMIN_PASSWORD=password

  haproxy:

    image: medicmobile/haproxy:rc-1.17
    volumes:
      - "${CHT_DATA:-medic-data}:/srv"
    environment:
      - COUCHDB_HOST=medic-os
      - HA_PASSWORD=password

